export interface ListType {
  value: number | string;
  label: string;
}

export const citiesList: ListType[] = [
  { value: 'Ad-Dammām', label: 'Ad-Dammām' },
  { value: 'Ad-Dawādmī', label: 'Ad-Dawādmī' },
  { value: 'Ad-Dilam', label: 'Ad-Dilam' },
  { value: 'Ad-Diriyah', label: 'Ad-Diriyah' },
  { value: 'Afïf', label: 'Afïf' },
  { value: 'Al-Awāmiyah', label: 'Al-Awāmiyah' },
  { value: 'Al-Bāḥah', label: 'Al-Bāḥah' },
  { value: 'Al-Hufūf', label: 'Al-Hufūf' },
  { value: 'Al-Jubaīl', label: 'Al-Jubaīl' },
  { value: 'Al-Khafjī', label: 'Al-Khafjī' },
  { value: 'Al-Kharj', label: 'Al-Kharj' },
  { value: 'Al-Madīnah', label: 'Al-Madīnah' },
  { value: 'Al-Qaṭīf', label: 'Al-Qaṭīf' },
  { value: 'Al-Qunfudhah', label: 'Al-Qunfudhah' },
  { value: 'Al-Ulā', label: 'Al-Ulā' },
  { value: 'Al-Wajh', label: 'Al-Wajh' },
  { value: 'An-Nimāṣ', label: 'An-Nimāṣ' },
  { value: 'An-Nuayriyah', label: 'An-Nuayriyah' },
  { value: 'Arar', label: 'Arar' },
  { value: 'Ar-Riyāḍ', label: 'Ar-Riyāḍ' },
  { value: 'Aṭ-Ṭaif', label: 'Aṭ-Ṭaif' },
  { value: 'Aẓ-Ẓahrān', label: 'Aẓ-Ẓahrān' },
  { value: 'Az-Zulfī', label: 'Az-Zulfī' },
  { value: 'Bīshah', label: 'Bīshah' },
  { value: 'Buraydah', label: 'Buraydah' },
  { value: 'Dūmat al-Jandal', label: 'Dūmat al-Jandal' },
  { value: 'Ḥafar al-Bāṭin', label: 'Ḥafar al-Bāṭin' },
  { value: 'Hail', label: 'Hail' },
  { value: 'Jiddah', label: 'Jiddah' },
  { value: 'Jīzān', label: 'Jīzān' },
  { value: 'Khamis Mushait', label: 'Khamis Mushait' },
  { value: 'Makkah', label: 'Makkah' },
  { value: 'Najran', label: 'Najran' },
  { value: 'Rābigh', label: 'Rābigh' },
  { value: 'Rafḥā', label: 'Rafḥā' },
  { value: 'Saīhāt', label: 'Saīhāt' },
  { value: 'Sakākā', label: 'Sakākā' },
  { value: 'Tabouk', label: 'Tabouk' },
];

export const facilitiesList: ListType[] = [
  { value: 'Information desk', label: 'Information desk' },
  { value: 'Indoor pool', label: 'Indoor pool' },
  { value: 'Outdoor pool', label: 'Outdoor pool' },
  { value: 'Fitness center', label: 'Fitness center' },
  { value: 'Sauna', label: 'Sauna' },
  { value: 'Business centre', label: 'Business centre' },
  { value: 'Tennis courts', label: 'Tennis courts' },
  { value: 'Garden', label: 'Garden' },
  { value: 'Beach', label: 'Beach' },
  { value: 'Night club', label: 'Night club' },
  { value: 'Café', label: 'Café' },
  { value: 'Bar and lounge', label: 'Bar and lounge' },
  { value: 'Conference facilities', label: 'Conference facilities' },
  { value: 'Shops', label: 'Shops' },
  { value: 'Laundry', label: 'Laundry' },
  { value: 'Disabled facilities', label: 'Disabled facilities' },
  { value: 'Meeting facilities', label: 'Meeting facilities' },
  { value: 'VIP room facilities', label: 'VIP room facilities' },
  { value: 'Spa', label: 'Spa' },
  { value: 'Massage', label: 'Massage' },
  { value: 'Hammam', label: 'Hammam' },
];
